/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DownloadLinks {
  'androidApk' : string,
  'androidTv' : string,
  'fireTv' : string,
  'appStore' : string,
  'googlePlay' : string,
}
export interface Review {
  'id' : bigint,
  'name' : string,
  'submittedAt' : Time,
  'comment' : string,
  'rating' : bigint,
}
export interface ReviewInput {
  'name' : string,
  'comment' : string,
  'rating' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getDownloadLinks' : ActorMethod<[], DownloadLinks>,
  'getReviewCount' : ActorMethod<[], bigint>,
  'submitReview' : ActorMethod<[ReviewInput], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];