/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'submittedAt' : Time,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const DownloadLinks = IDL.Record({
  'androidApk' : IDL.Text,
  'androidTv' : IDL.Text,
  'fireTv' : IDL.Text,
  'appStore' : IDL.Text,
  'googlePlay' : IDL.Text,
});
export const ReviewInput = IDL.Record({
  'name' : IDL.Text,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getDownloadLinks' : IDL.Func([], [DownloadLinks], ['query']),
  'getReviewCount' : IDL.Func([], [IDL.Nat], ['query']),
  'submitReview' : IDL.Func([ReviewInput], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'submittedAt' : Time,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const DownloadLinks = IDL.Record({
    'androidApk' : IDL.Text,
    'androidTv' : IDL.Text,
    'fireTv' : IDL.Text,
    'appStore' : IDL.Text,
    'googlePlay' : IDL.Text,
  });
  const ReviewInput = IDL.Record({
    'name' : IDL.Text,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getDownloadLinks' : IDL.Func([], [DownloadLinks], ['query']),
    'getReviewCount' : IDL.Func([], [IDL.Nat], ['query']),
    'submitReview' : IDL.Func([ReviewInput], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };